import { 
  CodeBracketIcon, 
  ShareIcon, 
  AcademicCapIcon,
  EyeIcon 
} from '@heroicons/react/24/solid';

const Features = () => {
  const features = [
    {
      icon: <EyeIcon className="h-12 w-12" />,
      title: 'Visual Editor',
      description: 'Create HTML structure and CSS styling using intuitive drag-and-drop blocks. No coding experience required!',
      color: 'border-t-blockly-blue'
    },
    {
      icon: <CodeBracketIcon className="h-12 w-12" />,
      title: 'Real-time Code Preview',
      description: 'See the actual HTML and CSS code generated by your blocks. Learn how code works as you build.',
      color: 'border-t-blockly-green'
    },
    {
      icon: <ShareIcon className="h-12 w-12" />,
      title: 'Share & Collaborate',
      description: 'Share your creations with friends or collaborate on projects in real-time with our multiplayer mode.',
      color: 'border-t-blockly-red'
    },
    {
      icon: <AcademicCapIcon className="h-12 w-12" />,
      title: 'Educational Resources',
      description: 'Step-by-step tutorials and challenges designed to teach web development concepts in a fun way.',
      color: 'border-t-blockly-yellow'
    }
  ];

  return (
    <section id="features" className="bg-white py-20 rounded-t-3xl">
      <div className="mx-20 px-6 mt-10">
        <h2 className="text-4xl md:text-5xl font-bold text-center text-gray-900 mb-4">
          Powerful Features
        </h2>
        <div className="w-24 h-2 bg-linear-to-r from-blockly-blue to-blockly-green rounded-full mx-auto mb-16"></div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div 
              key={index} 
              className={`feature-card ${feature.color}`}
            >
              <div className="text-blockly-blue mb-6">
                {feature.icon}
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">
                {feature.title}
              </h3>
              <p className="text-gray-600">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;