export const categories = [
  {
    id: "html",
    title: "HTML",
    color: "#f97316",
    subcategories: [
      {
        id: "page",
        title: "Page",
        color: "#FF8500",
        topics: [
          {
            id: "html-tag",
            title: "<html>",
            description: "The root element of an HTML page. Every HTML document must have one.",
            syntax: `<!DOCTYPE html>\n<html lang="en">\n  ...\n</html>`,
            notes: [
              "Always include the `lang` attribute for accessibility and SEO.",
              "Must contain exactly one `<head>` and one `<body>` element.",
            ],
            example: `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <title>My Page</title>\n  </head>\n  <body>\n    <p>Hello World</p>\n  </body>\n</html>`,
          },
          {
            id: "head-tag",
            title: "<head>",
            description: "Contains machine-readable meta-information about the document: title, scripts, stylesheets.",
            syntax: `<head>\n  <meta charset="UTF-8" />\n  <title>Page Title</title>\n  <link rel="stylesheet" href="style.css" />\n</head>`,
            notes: [
              "Content inside `<head>` is NOT displayed on the page.",
              "Always set `<meta charset='UTF-8'>` as the first child.",
            ],
            example: `<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>My Website</title>\n  <link rel="stylesheet" href="styles.css" />\n</head>`,
          },
          {
            id: "body-tag",
            title: "<body>",
            description: "Contains all the visible content of the HTML document — text, images, links, and more.",
            syntax: `<body>\n  <!-- visible content here -->\n</body>`,
            notes: [
              "There can only be ONE `<body>` element per HTML document.",
              "All user-visible content lives here.",
            ],
            example: `<body>\n  <h1>Welcome!</h1>\n  <p>This is a paragraph.</p>\n  <img src="photo.jpg" alt="A photo" />\n</body>`,
          },
          {
            id: "title-tag",
            title: "<title>",
            description: "Sets the title shown in the browser tab and used by search engines.",
            syntax: `<title>Page Title Here</title>`,
            notes: [
              "Should be unique per page for SEO.",
              "Recommended length: 50–60 characters.",
            ],
            example: `<head>\n  <title>WebbedSite – Learn Web Dev</title>\n</head>`,
          },
        ],
      },
      {
        id: "structure",
        title: "Structure",
        color: "#7b68ee",
        topics: [
          {
            id: "div",
            title: "<div>",
            description: "A generic block-level container with no semantic meaning. Used for grouping and styling.",
            syntax: `<div class="container">\n  ...\n</div>`,
            notes: ["Prefer semantic elements like `<section>` or `<article>` when the content has meaning."],
            example: `<div class="card">\n  <h2>Title</h2>\n  <p>Card content goes here.</p>\n</div>`,
          },
          {
            id: "header",
            title: "<header>",
            description: "Represents introductory content or a group of navigational links.",
            syntax: `<header>\n  <h1>Site Title</h1>\n  <nav>...</nav>\n</header>`,
            notes: ["Can appear multiple times — once for the page, once inside `<article>` or `<section>`."],
            example: `<header>\n  <h1>WebbedSite</h1>\n  <nav>\n    <a href="/">Home</a>\n    <a href="/docs">Docs</a>\n  </nav>\n</header>`,
          },
          {
            id: "nav",
            title: "<nav>",
            description: "Defines a set of navigation links.",
            syntax: `<nav>\n  <a href="/">Home</a>\n  <a href="/about">About</a>\n</nav>`,
            notes: ["Not all links need to be inside `<nav>` — only major navigation blocks."],
            example: `<nav aria-label="Main navigation">\n  <ul>\n    <li><a href="/">Home</a></li>\n    <li><a href="/docs">Docs</a></li>\n  </ul>\n</nav>`,
          },
          {
            id: "main",
            title: "<main>",
            description: "Specifies the main content of the document. Should be unique and not repeated.",
            syntax: `<main>\n  <h1>Page Heading</h1>\n  <p>Primary content...</p>\n</main>`,
            notes: ["Only ONE `<main>` per page.", "Helps screen readers jump directly to content."],
            example: `<body>\n  <header>...</header>\n  <main>\n    <h1>Welcome</h1>\n    <p>Main content here.</p>\n  </main>\n  <footer>...</footer>\n</body>`,
          },
          {
            id: "footer",
            title: "<footer>",
            description: "Represents a footer for its nearest sectioning content or root element.",
            syntax: `<footer>\n  <p>&copy; 2024 My Site</p>\n</footer>`,
            notes: ["Can contain author info, related links, copyright info."],
            example: `<footer>\n  <p>Made with ❤️ by WebbedSite</p>\n  <nav>\n    <a href="/privacy">Privacy</a>\n    <a href="/terms">Terms</a>\n  </nav>\n</footer>`,
          },
          {
            id: "section",
            title: "<section>",
            description: "Defines a thematic grouping of content, typically with a heading.",
            syntax: `<section>\n  <h2>Section Title</h2>\n  <p>...</p>\n</section>`,
            notes: ["Each section should ideally have a heading.", "Use `<div>` if there is no semantic meaning."],
            example: `<section id="about">\n  <h2>About Us</h2>\n  <p>We teach web development.</p>\n</section>`,
          },
          {
            id: "article",
            title: "<article>",
            description: "Represents self-contained content that could be distributed independently (blog post, news article).",
            syntax: `<article>\n  <h2>Post Title</h2>\n  <p>Content...</p>\n</article>`,
            notes: ["An `<article>` should make sense on its own, even outside the page."],
            example: `<article>\n  <h2>Getting Started with HTML</h2>\n  <p>HTML is the language of the web...</p>\n</article>`,
          },
          {
            id: "br",
            title: "<br>",
            description: "Inserts a line break. Self-closing.",
            syntax: `<p>First line<br />Second line</p>`,
            notes: ["Don't use `<br>` for spacing — use CSS margins/padding instead."],
            example: `<p>123 Main St<br />Springfield, IL 62701</p>`,
          },
          {
            id: "hr",
            title: "<hr>",
            description: "Represents a thematic break between paragraph-level elements.",
            syntax: `<hr />`,
            notes: ["Self-closing.", "Use CSS to style its color, width, or thickness."],
            example: `<p>First section content.</p>\n<hr />\n<p>Second section content.</p>`,
          },
        ],
      },
      {
        id: "text",
        title: "Text",
        color: "#4a90e2",
        topics: [
          {
            id: "headings",
            title: "<h1>–<h6>",
            description: "Heading elements from most important (h1) to least important (h6).",
            syntax: `<h1>Main Title</h1>\n<h2>Subtitle</h2>\n<h3>Section</h3>`,
            notes: ["Use only ONE `<h1>` per page.", "Don't skip levels — go h1 → h2 → h3 in order."],
            example: `<h1>WebbedSite Docs</h1>\n<h2>HTML</h2>\n<h3>Page Structure</h3>`,
          },
          {
            id: "p",
            title: "<p>",
            description: "Defines a paragraph of text.",
            syntax: `<p>Your text here.</p>`,
            notes: ["Browsers add default top and bottom margin to `<p>` elements."],
            example: `<p>HTML stands for HyperText Markup Language.</p>\n<p>It is the standard for building web pages.</p>`,
          },
          {
            id: "span",
            title: "<span>",
            description: "An inline container used to style or target a part of text.",
            syntax: `<p>This is <span class="highlight">important</span>.</p>`,
            notes: ["Unlike `<div>`, `<span>` is inline and doesn't break the text flow."],
            example: `<p>Score: <span style="color: green; font-weight: bold;">100</span>/100</p>`,
          },
          {
            id: "a",
            title: "<a>",
            description: "Creates a hyperlink to another page, file, email, or location.",
            syntax: `<a href="https://example.com">Link text</a>`,
            notes: [
              "Use `target='_blank'` to open in a new tab (add `rel='noopener noreferrer'` for security).",
              "Can link to page anchors with `href='#section-id'`.",
            ],
            example: `<a href="https://webbedsite.com" target="_blank" rel="noopener noreferrer">\n  Visit WebbedSite\n</a>`,
          },
          {
            id: "strong",
            title: "<strong>",
            description: "Marks text as strongly important. Renders as bold by default.",
            syntax: `<strong>Important text</strong>`,
            notes: ["Use `<strong>` for semantic importance, not just for bold styling — use CSS `font-weight` for that."],
            example: `<p><strong>Warning:</strong> Save your work before leaving.</p>`,
          },
          {
            id: "em",
            title: "<em>",
            description: "Marks text with stress emphasis. Renders as italic by default.",
            syntax: `<em>emphasized text</em>`,
            notes: ["Use `<em>` for semantic emphasis; use CSS `font-style: italic` for purely visual italics."],
            example: `<p>You should <em>always</em> close your HTML tags.</p>`,
          },
        ],
      },
      {
        id: "attributes",
        title: "Attributes",
        color: "#F5B945",
        topics: [
          {
            id: "class-attr",
            title: "class",
            description: "Assigns one or more CSS class names to an element for styling or targeting.",
            syntax: `<div class="card highlighted"></div>`,
            notes: ["Multiple classes separated by spaces.", "Used heavily with CSS and JavaScript."],
            example: `<p class="text-lg font-bold text-blue-500">Styled paragraph</p>`,
          },
          {
            id: "id-attr",
            title: "id",
            description: "Gives an element a unique identifier within the page.",
            syntax: `<div id="main-content"></div>`,
            notes: ["IDs must be unique per page.", "Used for anchor links (`href='#id'`) and JavaScript targeting."],
            example: `<section id="about">\n  <h2>About</h2>\n</section>\n\n<a href="#about">Go to About</a>`,
          },
          {
            id: "style-attr",
            title: "style",
            description: "Applies inline CSS styles directly to an element.",
            syntax: `<p style="color: red; font-size: 18px;">Text</p>`,
            notes: ["Inline styles have the highest specificity.", "Avoid overusing — prefer external CSS."],
            example: `<div style="background-color: #f0f0f0; padding: 16px; border-radius: 8px;">\n  Inline styled box\n</div>`,
          },
          {
            id: "other-attrs",
            title: "attributes",
            description: "HTML elements support many other attributes: `href`, `src`, `alt`, `type`, `placeholder`, `disabled`, `required`, and more.",
            syntax: `<input type="text" placeholder="Enter name" required />\n<img src="photo.jpg" alt="A cat" />`,
            notes: [
              "Boolean attributes (like `disabled`, `required`) don't need a value.",
              "Always provide `alt` on `<img>` for accessibility.",
            ],
            example: `<input\n  type="email"\n  id="email"\n  name="email"\n  placeholder="you@example.com"\n  required\n/>`,
          },
        ],
      },
      {
        id: "media",
        title: "Media",
        color: "#D94452",
        topics: [
          {
            id: "img",
            title: "<img>",
            description: "Embeds an image into the page. Self-closing.",
            syntax: `<img src="image.jpg" alt="Description" />`,
            notes: ["Always include `alt` for accessibility.", "Use `width` and `height` attributes to prevent layout shift."],
            example: `<img\n  src="https://via.placeholder.com/300x200"\n  alt="A placeholder image"\n  width="300"\n  height="200"\n/>`,
          },
          {
            id: "audio",
            title: "<audio>",
            description: "Embeds audio content with browser-native controls.",
            syntax: `<audio src="sound.mp3" controls></audio>`,
            notes: ["Use multiple `<source>` elements for browser compatibility.", "`controls` attribute shows play/pause UI."],
            example: `<audio controls>\n  <source src="audio.mp3" type="audio/mpeg" />\n  <source src="audio.ogg" type="audio/ogg" />\n  Your browser does not support audio.\n</audio>`,
          },
          {
            id: "video",
            title: "<video>",
            description: "Embeds a video with browser-native controls.",
            syntax: `<video src="video.mp4" controls width="640"></video>`,
            notes: ["Add `autoplay muted` for background videos (must be muted for autoplay to work).", "Always provide a fallback message."],
            example: `<video controls width="640" height="360">\n  <source src="video.mp4" type="video/mp4" />\n  Your browser does not support video.\n</video>`,
          },
        ],
      },
      {
        id: "forms",
        title: "Forms",
        color: "#20b2aa",
        topics: [
          {
            id: "form",
            title: "<form>",
            description: "Creates an HTML form for collecting user input.",
            syntax: `<form action="/submit" method="POST">\n  ...\n</form>`,
            notes: ["`action` is where data is sent; `method` is GET or POST.", "In React, forms are typically handled with `onSubmit` and `preventDefault()`."],
            example: `<form action="/login" method="POST">\n  <input type="email" name="email" />\n  <button type="submit">Login</button>\n</form>`,
          },
          {
            id: "label",
            title: "<label>",
            description: "Associates a text label with a form control for accessibility.",
            syntax: `<label for="email">Email</label>\n<input id="email" type="email" />`,
            notes: ["The `for` attribute must match the `id` of the input.", "Clicking the label focuses the input."],
            example: `<div>\n  <label for="username">Username</label>\n  <input id="username" type="text" name="username" />\n</div>`,
          },
          {
            id: "input",
            title: "<input>",
            description: "Creates an interactive field for user data. Self-closing with many type variants.",
            syntax: `<input type="text" name="name" placeholder="Your name" />`,
            notes: ["Common types: `text`, `email`, `password`, `number`, `checkbox`, `radio`, `file`, `submit`.", "Self-closing element."],
            example: `<input type="text" name="firstName" placeholder="First name" required />\n<input type="password" name="pass" placeholder="Password" />\n<input type="checkbox" id="agree" name="agree" />\n<label for="agree">I agree</label>`,
          },
          {
            id: "textarea",
            title: "<textarea>",
            description: "Multi-line plain text input.",
            syntax: `<textarea name="message" rows="4" cols="50"></textarea>`,
            notes: ["Unlike `<input>`, `<textarea>` has a closing tag.", "Use CSS `resize: none` to disable manual resizing."],
            example: `<label for="bio">Bio</label>\n<textarea id="bio" name="bio" rows="4" placeholder="Tell us about yourself..."></textarea>`,
          },
          {
            id: "button",
            title: "<button>",
            description: "A clickable button element.",
            syntax: `<button type="submit">Submit</button>`,
            notes: ["Types: `submit` (default), `reset`, `button`.", "Use `type='button'` inside forms to prevent accidental submission."],
            example: `<button type="submit">Save Changes</button>\n<button type="reset">Clear</button>\n<button type="button" onclick="doSomething()">Click Me</button>`,
          },
        ],
      },
      {
        id: "tables",
        title: "Tables",
        color: "#9b59b6",
        topics: [
          {
            id: "table",
            title: "<table>",
            description: "Defines an HTML table for displaying tabular data.",
            syntax: `<table>\n  <thead>...</thead>\n  <tbody>...</tbody>\n</table>`,
            notes: ["Never use tables for layout — use CSS Grid or Flexbox.", "Always include `<thead>` and `<tbody>` for accessibility."],
            example: `<table>\n  <thead>\n    <tr>\n      <th>Name</th>\n      <th>Score</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Alice</td>\n      <td>95</td>\n    </tr>\n  </tbody>\n</table>`,
          },
          {
            id: "th",
            title: "<th>",
            description: "Table header cell. Bold and centered by default.",
            syntax: `<th scope="col">Column Name</th>`,
            notes: ["Use `scope='col'` or `scope='row'` for accessibility."],
            example: `<tr>\n  <th scope="col">Student</th>\n  <th scope="col">Grade</th>\n  <th scope="col">Date</th>\n</tr>`,
          },
          {
            id: "tr",
            title: "<tr>",
            description: "Defines a row in a table.",
            syntax: `<tr>\n  <td>Cell 1</td>\n  <td>Cell 2</td>\n</tr>`,
            notes: ["Rows contain `<th>` or `<td>` cells."],
            example: `<tr>\n  <td>Alice</td>\n  <td>90%</td>\n  <td>2024-01-15</td>\n</tr>`,
          },
          {
            id: "td",
            title: "<td>",
            description: "A standard table data cell.",
            syntax: `<td>Data</td>`,
            notes: ["Use `colspan` and `rowspan` to merge cells."],
            example: `<td colspan="2">Spans two columns</td>\n<td rowspan="3">Spans three rows</td>`,
          },
        ],
      },
      {
        id: "lists",
        title: "Lists",
        color: "#ff6b6b",
        topics: [
          {
            id: "li",
            title: "<li>",
            description: "A list item, used inside `<ul>` or `<ol>`.",
            syntax: `<li>Item text</li>`,
            notes: ["Must be a direct child of `<ul>`, `<ol>`, or `<menu>`."],
            example: `<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n  <li>JavaScript</li>\n</ul>`,
          },
          {
            id: "ul",
            title: "<ul>",
            description: "An unordered (bulleted) list.",
            syntax: `<ul>\n  <li>Item</li>\n</ul>`,
            notes: ["Renders with bullet points by default — override with CSS `list-style-type`."],
            example: `<ul>\n  <li>Eggs</li>\n  <li>Milk</li>\n  <li>Bread</li>\n</ul>`,
          },
          {
            id: "ol",
            title: "<ol>",
            description: "An ordered (numbered) list.",
            syntax: `<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>`,
            notes: ["Use `start` attribute to begin from a number other than 1.", "Use `type` to change numbering style: `1`, `A`, `a`, `I`, `i`."],
            example: `<ol type="A">\n  <li>Plan</li>\n  <li>Build</li>\n  <li>Deploy</li>\n</ol>`,
          },
          {
            id: "select",
            title: "<select>",
            description: "Creates a dropdown list.",
            syntax: `<select name="color">\n  <option value="red">Red</option>\n</select>`,
            notes: ["Use `multiple` attribute to allow multiple selections.", "Wrap in `<label>` for accessibility."],
            example: `<label for="lang">Language</label>\n<select id="lang" name="lang">\n  <option value="html">HTML</option>\n  <option value="css">CSS</option>\n  <option value="js">JavaScript</option>\n</select>`,
          },
          {
            id: "option",
            title: "<option>",
            description: "An option in a `<select>` dropdown.",
            syntax: `<option value="value">Display Text</option>`,
            notes: ["Use `selected` attribute to pre-select an option.", "Use `disabled` for placeholder options."],
            example: `<select>\n  <option value="" disabled selected>Choose one...</option>\n  <option value="beginner">Beginner</option>\n  <option value="advanced">Advanced</option>\n</select>`,
          },
        ],
      },
    ],
  },
  {
    id: "css",
    title: "CSS",
    color: "#4285f4",
    subcategories: [
      {
        id: "selectors",
        title: "Selectors",
        color: "#FF8500",
        topics: [
          {
            id: "element-selector",
            title: "element",
            description: "Selects all elements of a given HTML tag type.",
            syntax: `p { color: navy; }`,
            notes: ["Targets every matching element on the page.", "Low specificity — easily overridden."],
            example: `h1 {\n  font-size: 2rem;\n  font-weight: bold;\n}\n\np {\n  line-height: 1.6;\n  color: #333;\n}`,
          },
          {
            id: "class-selector",
            title: "class",
            description: "Selects elements with a specific class attribute. Prefix with a dot (`.`).",
            syntax: `.class-name { property: value; }`,
            notes: ["Multiple elements can share the same class.", "An element can have multiple classes."],
            example: `.card {\n  border: 1px solid #ddd;\n  border-radius: 8px;\n  padding: 16px;\n}\n\n.text-bold {\n  font-weight: 700;\n}`,
          },
          {
            id: "id-selector",
            title: "id",
            description: "Selects a single element by its unique ID. Prefix with a hash (`#`).",
            syntax: `#element-id { property: value; }`,
            notes: ["IDs should be unique per page.", "High specificity — harder to override. Prefer classes."],
            example: `#main-nav {\n  display: flex;\n  gap: 16px;\n  background: #fff;\n}`,
          },
          {
            id: "universal-selector",
            title: "universal (*)",
            description: "Selects every element on the page.",
            syntax: `* { box-sizing: border-box; }`,
            notes: ["Commonly used in CSS resets.", "Can impact performance if overused with complex properties."],
            example: `* {\n  box-sizing: border-box;\n  margin: 0;\n  padding: 0;\n}`,
          },
          {
            id: "grouping-selector",
            title: "grouping (,)",
            description: "Applies the same rules to multiple selectors at once.",
            syntax: `h1, h2, h3 { font-family: 'Georgia', serif; }`,
            notes: ["Reduces repetition.", "Any selector type can be grouped."],
            example: `h1, h2, h3, h4 {\n  font-weight: 700;\n  line-height: 1.2;\n  color: #111;\n}`,
          },
          {
            id: "descendant-selector",
            title: "descendant",
            description: "Selects elements that are descendants (any level deep) of a given element.",
            syntax: `parent child { property: value; }`,
            notes: ["Separated by a space.", "Targets ALL matching descendants, not just direct children."],
            example: `.card p {\n  color: #555;\n  font-size: 0.9rem;\n}`,
          },
          {
            id: "child-selector",
            title: "child (>)",
            description: "Selects only DIRECT children of a parent element.",
            syntax: `parent > child { property: value; }`,
            notes: ["More specific than the descendant selector.", "Does not select grandchildren."],
            example: `ul > li {\n  list-style: none;\n  padding: 8px 0;\n}`,
          },
          {
            id: "adj-sibling-selector",
            title: "adjacent sibling (+)",
            description: "Selects the immediately following sibling element.",
            syntax: `element + adjacent { property: value; }`,
            notes: ["Only targets the FIRST sibling immediately after."],
            example: `h2 + p {\n  margin-top: 4px;\n  color: #666;\n}`,
          },
          {
            id: "gen-sibling-selector",
            title: "general sibling (~)",
            description: "Selects ALL following siblings of an element.",
            syntax: `element ~ siblings { property: value; }`,
            notes: ["Targets all siblings that come after, not just the first."],
            example: `h2 ~ p {\n  color: #555;\n}`,
          },
        ],
      },
      {
        id: "text-fonts",
        title: "Text & Fonts",
        color: "#4a90e2",
        topics: [
          {
            id: "color-prop",
            title: "color",
            description: "Sets the foreground color of text.",
            syntax: `color: value;`,
            notes: ["Accepts: named colors, hex (`#f00`), RGB (`rgb(255,0,0)`), HSL, `transparent`."],
            example: `.heading {\n  color: #1a202c;\n}\n\n.muted {\n  color: rgb(100, 116, 139);\n}`,
          },
          {
            id: "font-family",
            title: "font-family",
            description: "Specifies the typeface for text. Always include a generic fallback.",
            syntax: `font-family: 'Font Name', fallback, generic;`,
            notes: ["Wrap font names with spaces in quotes.", "Generic families: `serif`, `sans-serif`, `monospace`, `cursive`."],
            example: `body {\n  font-family: 'Inter', 'Segoe UI', sans-serif;\n}\n\ncode {\n  font-family: 'Fira Code', 'Courier New', monospace;\n}`,
          },
          {
            id: "font-size",
            title: "font-size",
            description: "Sets the size of the font.",
            syntax: `font-size: value;`,
            notes: ["Prefer `rem` for accessibility (scales with user browser settings).", "Common units: `px`, `rem`, `em`, `%`, `vw`."],
            example: `html {\n  font-size: 16px; /* 1rem = 16px */\n}\n\nh1 { font-size: 2rem; }    /* 32px */\np  { font-size: 1rem; }    /* 16px */\nsmall { font-size: 0.875rem; } /* 14px */`,
          },
          {
            id: "font-weight",
            title: "font-weight",
            description: "Controls the thickness (boldness) of the font.",
            syntax: `font-weight: value;`,
            notes: ["Numeric values: `100` (thin) → `900` (black). `400` = normal, `700` = bold."],
            example: `.normal   { font-weight: 400; }\n.semibold { font-weight: 600; }\n.bold     { font-weight: 700; }\n.black    { font-weight: 900; }`,
          },
          {
            id: "line-height",
            title: "line-height",
            description: "Sets the height of a line of text. Affects readability significantly.",
            syntax: `line-height: value;`,
            notes: ["Unitless values (e.g., `1.5`) are relative to the element's font-size — preferred.", "Recommended for body text: `1.5`–`1.7`."],
            example: `p {\n  line-height: 1.6;\n}\n\nh1 {\n  line-height: 1.2;\n}`,
          },
          {
            id: "text-align",
            title: "text-align",
            description: "Aligns inline content horizontally within a block element.",
            syntax: `text-align: left | center | right | justify;`,
            notes: ["`justify` adds extra spacing between words to fill the line.", "Only affects inline content, not the block itself."],
            example: `.hero-title {\n  text-align: center;\n}\n\n.article-body {\n  text-align: left;\n}`,
          },
          {
            id: "text-decoration",
            title: "text-decoration",
            description: "Adds visual decoration to text: underline, overline, line-through.",
            syntax: `text-decoration: none | underline | line-through | overline;`,
            notes: ["Commonly used to remove the underline from `<a>` tags.", "Can combine with color and style: `underline dotted red`."],
            example: `a {\n  text-decoration: none;\n}\n\na:hover {\n  text-decoration: underline;\n}\n\n.strikethrough {\n  text-decoration: line-through;\n}`,
          },
          {
            id: "text-transform",
            title: "text-transform",
            description: "Changes the capitalization of text.",
            syntax: `text-transform: none | uppercase | lowercase | capitalize;`,
            notes: ["`capitalize` capitalizes the first letter of each word.", "Does not change the underlying HTML text."],
            example: `.badge {\n  text-transform: uppercase;\n  letter-spacing: 0.1em;\n}\n\n.title {\n  text-transform: capitalize;\n}`,
          },
          {
            id: "letter-spacing",
            title: "letter-spacing",
            description: "Sets the spacing between characters.",
            syntax: `letter-spacing: value;`,
            notes: ["Positive values spread letters apart; negative values bring them closer.", "Commonly used with `text-transform: uppercase` for headers."],
            example: `.heading {\n  letter-spacing: 0.05em;\n}\n\n.spread {\n  letter-spacing: 0.2em;\n  text-transform: uppercase;\n}`,
          },
        ],
      },
      {
        id: "box-model",
        title: "Box Model",
        color: "#7b68ee",
        topics: [
          {
            id: "margin",
            title: "margin",
            description: "Space OUTSIDE the border of an element.",
            syntax: `margin: top right bottom left;\nmargin: 16px;\nmargin: 8px 16px;`,
            notes: ["Margins can collapse between adjacent block elements.", "Use `margin: 0 auto` to center block elements horizontally."],
            example: `.card {\n  margin: 16px;\n}\n\n.centered {\n  margin: 0 auto;\n  max-width: 640px;\n}`,
          },
          {
            id: "padding",
            title: "padding",
            description: "Space INSIDE the border, between the border and the content.",
            syntax: `padding: top right bottom left;\npadding: 16px;\npadding: 8px 16px;`,
            notes: ["Padding is inside the element — it adds to the background area.", "With `box-sizing: border-box`, padding is included in width/height."],
            example: `.button {\n  padding: 10px 24px;\n}\n\n.card {\n  padding: 24px;\n}`,
          },
          {
            id: "border",
            title: "border",
            description: "Sets the style, width, and color of an element's border.",
            syntax: `border: width style color;\nborder: 1px solid #ccc;`,
            notes: ["Can target sides individually: `border-top`, `border-right`, etc.", "Shorthand: `width` `style` `color`."],
            example: `.input {\n  border: 1px solid #d1d5db;\n  border-radius: 6px;\n}\n\n.input:focus {\n  border-color: #3b82f6;\n  outline: none;\n}`,
          },
          {
            id: "width",
            title: "width",
            description: "Sets the width of an element's content area.",
            syntax: `width: value;`,
            notes: ["`max-width` is great for responsive layouts.", "With `box-sizing: border-box`, padding/border are included in the width."],
            example: `.container {\n  width: 100%;\n  max-width: 1200px;\n  margin: 0 auto;\n}`,
          },
          {
            id: "height",
            title: "height",
            description: "Sets the height of an element's content area.",
            syntax: `height: value;`,
            notes: ["Avoid fixed heights for text containers — use `min-height` instead.", "`100vh` = full viewport height."],
            example: `.hero {\n  min-height: 100vh;\n  display: flex;\n  align-items: center;\n}`,
          },
          {
            id: "box-sizing",
            title: "box-sizing",
            description: "Controls how the total width/height of an element is calculated.",
            syntax: `box-sizing: content-box | border-box;`,
            notes: ["`content-box` (default): width doesn't include padding/border.", "`border-box`: width INCLUDES padding and border — almost always preferred."],
            example: `/* Apply globally — highly recommended */\n*, *::before, *::after {\n  box-sizing: border-box;\n}`,
          },
        ],
      },
      {
        id: "backgrounds",
        title: "Backgrounds",
        color: "#F5B945",
        topics: [
          { id: "bg-color", title: "background-color", description: "Sets the background color of an element.", syntax: `background-color: value;`, notes: ["Accepts all CSS color values.", "Use `transparent` for no background."], example: `.card {\n  background-color: #ffffff;\n}\n\n.dark-section {\n  background-color: #0f172a;\n  color: white;\n}` },
          { id: "bg-image", title: "background-image", description: "Sets one or more background images, including CSS gradients.", syntax: `background-image: url('image.jpg');\nbackground-image: linear-gradient(to right, #f97316, #f43f5e);`, notes: ["Multiple images can be layered, separated by commas.", "Gradients (`linear-gradient`, `radial-gradient`) count as images."], example: `.hero {\n  background-image: linear-gradient(\n    135deg,\n    #667eea 0%,\n    #764ba2 100%\n  );\n}` },
          { id: "bg-repeat", title: "background-repeat", description: "Controls how background images tile.", syntax: `background-repeat: repeat | no-repeat | repeat-x | repeat-y;`, notes: ["Use `no-repeat` for most photos and large images."], example: `.texture {\n  background-image: url('grain.png');\n  background-repeat: repeat;\n}\n\n.hero {\n  background-repeat: no-repeat;\n}` },
          { id: "bg-position", title: "background-position", description: "Sets the starting position of the background image.", syntax: `background-position: center center;\nbackground-position: top left;\nbackground-position: 50% 50%;`, notes: ["Keywords: `top`, `bottom`, `left`, `right`, `center`."], example: `.hero {\n  background-position: center center;\n}` },
          { id: "bg-size", title: "background-size", description: "Controls the size of the background image.", syntax: `background-size: auto | cover | contain | 100px 200px;`, notes: ["`cover`: fills the element (may crop).", "`contain`: fits the whole image (may leave gaps)."], example: `.hero {\n  background-size: cover;\n}\n\n.logo-bg {\n  background-size: contain;\n  background-repeat: no-repeat;\n}` },
          { id: "bg-attachment", title: "background-attachment", description: "Controls whether the background scrolls with the page or is fixed.", syntax: `background-attachment: scroll | fixed | local;`, notes: ["`fixed` creates a parallax effect.", "Can cause performance issues on mobile."], example: `.parallax {\n  background-attachment: fixed;\n  background-size: cover;\n}` },
        ],
      },
      {
        id: "flexbox",
        title: "Flexbox",
        color: "#D94452",
        topics: [
          { id: "display-flex", title: "display: flex", description: "Turns an element into a flex container, enabling flexbox layout on its children.", syntax: `display: flex;`, notes: ["Children become flex items automatically.", "Default direction is row (horizontal)."], example: `.nav {\n  display: flex;\n  gap: 16px;\n}` },
          { id: "flex-direction", title: "flex-direction", description: "Sets the main axis direction for flex items.", syntax: `flex-direction: row | column | row-reverse | column-reverse;`, notes: ["`row` (default): left to right.", "`column`: top to bottom."], example: `.sidebar {\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n}` },
          { id: "justify-content", title: "justify-content", description: "Aligns flex items along the MAIN axis.", syntax: `justify-content: flex-start | flex-end | center | space-between | space-around | space-evenly;`, notes: ["`space-between`: equal space between items, none at edges.", "`center`: perfect centering."], example: `.toolbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}` },
          { id: "align-items", title: "align-items", description: "Aligns flex items along the CROSS axis.", syntax: `align-items: stretch | flex-start | flex-end | center | baseline;`, notes: ["`stretch` (default): items stretch to fill the container.", "`center`: vertically centered."], example: `.card {\n  display: flex;\n  align-items: center;\n  gap: 12px;\n}` },
          { id: "align-content", title: "align-content", description: "Aligns multiple rows of flex items on the cross axis (only when there's wrapping).", syntax: `align-content: flex-start | flex-end | center | space-between | stretch;`, notes: ["Only has effect when `flex-wrap: wrap` is set and there are multiple lines."], example: `.grid {\n  display: flex;\n  flex-wrap: wrap;\n  align-content: space-between;\n}` },
          { id: "flex-wrap", title: "flex-wrap", description: "Controls whether flex items wrap to new lines.", syntax: `flex-wrap: nowrap | wrap | wrap-reverse;`, notes: ["`nowrap` (default): all items stay on one line, may overflow.", "`wrap`: items wrap to the next line."], example: `.tag-list {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 8px;\n}` },
          { id: "flex-grow", title: "flex-grow", description: "Allows a flex item to grow to fill available space.", syntax: `flex-grow: number; /* default: 0 */`, notes: ["A value of `1` means the item will take up remaining space.", "Higher values take proportionally more space."], example: `.input-wrapper {\n  display: flex;\n}\n\n.input-wrapper input {\n  flex-grow: 1; /* Takes all remaining space */\n}\n\n.input-wrapper button {\n  flex-grow: 0; /* Stays at natural size */\n}` },
          { id: "flex-shrink", title: "flex-shrink", description: "Controls how much a flex item shrinks relative to others when space is tight.", syntax: `flex-shrink: number; /* default: 1 */`, notes: ["`0` prevents the item from shrinking.", "Higher values shrink more."], example: `.icon {\n  flex-shrink: 0; /* Never shrink the icon */\n  width: 24px;\n}` },
          { id: "flex-basis", title: "flex-basis", description: "Sets the initial main size of a flex item before growing/shrinking.", syntax: `flex-basis: auto | 200px | 50%;`, notes: ["Works like `width` in row direction, `height` in column direction.", "Often used in the shorthand: `flex: grow shrink basis`."], example: `.column {\n  flex: 1 1 200px; /* grow shrink basis */\n}` },
        ],
      },
      {
        id: "grid",
        title: "Grid",
        color: "#20b2aa",
        topics: [
          { id: "display-grid", title: "display: grid", description: "Turns an element into a CSS Grid container.", syntax: `display: grid;`, notes: ["Children become grid items.", "Combine with `grid-template-columns` to define the layout."], example: `.gallery {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 16px;\n}` },
          { id: "grid-template-columns", title: "grid-template-columns", description: "Defines the number and size of columns in the grid.", syntax: `grid-template-columns: 200px 1fr | repeat(3, 1fr) | auto;`, notes: ["`fr` = fractional unit of available space.", "`repeat(n, size)` is a shorthand for repeated tracks.", "`auto` sizes to content."], example: `/* 3 equal columns */\n.layout {\n  grid-template-columns: repeat(3, 1fr);\n}\n\n/* Sidebar + main */\n.page {\n  grid-template-columns: 250px 1fr;\n}` },
          { id: "grid-template-rows", title: "grid-template-rows", description: "Defines the number and size of rows.", syntax: `grid-template-rows: auto 1fr auto;`, notes: ["Works the same as `grid-template-columns` but for rows."], example: `.page-layout {\n  display: grid;\n  grid-template-rows: 60px 1fr 80px; /* header, main, footer */\n  min-height: 100vh;\n}` },
          { id: "grid-gap", title: "grid-gap (gap)", description: "Sets the spacing between grid cells. Use `gap` (the modern shorthand).", syntax: `gap: row-gap column-gap;\ngap: 16px;\ngap: 16px 24px;`, notes: ["`gap` is the modern property; `grid-gap` is the old name.", "Works in both Grid and Flexbox."], example: `.grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 24px;\n}` },
          { id: "grid-column", title: "grid-column", description: "Controls where an item starts and ends horizontally in the grid.", syntax: `grid-column: start / end;\ngrid-column: 1 / 3;\ngrid-column: 1 / -1; /* full width */`, notes: ["Negative values count from the end of the grid.", "`span N` means span N tracks."], example: `.full-width {\n  grid-column: 1 / -1; /* spans all columns */\n}\n\n.sidebar {\n  grid-column: 1 / 2;\n}` },
          { id: "grid-row", title: "grid-row", description: "Controls where an item starts and ends vertically in the grid.", syntax: `grid-row: start / end;`, notes: ["Works the same as `grid-column` but for rows."], example: `.featured {\n  grid-row: 1 / 3; /* spans 2 rows */\n}` },
          { id: "justify-items", title: "justify-items", description: "Aligns grid items horizontally within their cells.", syntax: `justify-items: start | end | center | stretch;`, notes: ["`stretch` (default) fills the cell.", "`center` centers the item within its cell."], example: `.grid {\n  display: grid;\n  justify-items: center;\n}` },
          { id: "align-items-grid", title: "align-items", description: "Aligns grid items vertically within their cells.", syntax: `align-items: start | end | center | stretch;`, notes: ["Same as `justify-items` but on the block/vertical axis."], example: `.grid {\n  display: grid;\n  align-items: center;\n}` },
        ],
      },
      {
        id: "positioning",
        title: "Positioning",
        color: "#9b59b6",
        topics: [
          { id: "position", title: "position", description: "Sets how an element is positioned in the document.", syntax: `position: static | relative | absolute | fixed | sticky;`, notes: ["`static` (default): normal flow.", "`relative`: offset from its normal position.", "`absolute`: removed from flow, positioned relative to nearest positioned ancestor.", "`fixed`: relative to viewport, stays on scroll.", "`sticky`: sticks to a position within its parent when scrolling."], example: `.tooltip {\n  position: relative;\n}\n\n.tooltip-content {\n  position: absolute;\n  top: 100%;\n  left: 0;\n}` },
          { id: "top-right-bottom-left", title: "top / right / bottom / left", description: "Offset properties used with positioned elements.", syntax: `top: value;\nright: value;\nbottom: value;\nleft: value;`, notes: ["Only works on elements with `position` other than `static`."], example: `.overlay {\n  position: fixed;\n  top: 0;\n  left: 0;\n  right: 0;\n  bottom: 0;\n  background: rgba(0,0,0,0.5);\n}` },
          { id: "z-index", title: "z-index", description: "Controls the stacking order of positioned elements.", syntax: `z-index: number;`, notes: ["Higher values appear on top.", "Only works on positioned elements (not `static`).", "Create stacking contexts carefully."], example: `.modal {\n  position: fixed;\n  z-index: 1000;\n}\n\n.tooltip {\n  position: absolute;\n  z-index: 50;\n}` },
          { id: "float", title: "float", description: "Floats an element to the left or right, allowing text to wrap around it.", syntax: `float: left | right | none;`, notes: ["Mostly used for text wrapping around images.", "Avoid using floats for layout — use Flexbox/Grid instead."], example: `.article img {\n  float: left;\n  margin: 0 16px 16px 0;\n}` },
          { id: "clear", title: "clear", description: "Specifies which sides of an element cannot be adjacent to floating elements.", syntax: `clear: left | right | both | none;`, notes: ["Used to push content below floated elements."], example: `.clearfix::after {\n  content: '';\n  display: table;\n  clear: both;\n}` },
        ],
      },
      {
        id: "animations",
        title: "Animations & Transitions",
        color: "#ff6b6b",
        topics: [
          { id: "transition", title: "transition", description: "Animates property changes smoothly over time.", syntax: `transition: property duration timing-function delay;`, notes: ["Multiple properties separated by commas.", "Common shorthand: `transition: all 0.3s ease`."], example: `.button {\n  background: #3b82f6;\n  transition: background 0.2s ease, transform 0.2s ease;\n}\n\n.button:hover {\n  background: #2563eb;\n  transform: translateY(-2px);\n}` },
          { id: "transition-duration", title: "transition-duration", description: "Sets how long the transition takes.", syntax: `transition-duration: 300ms | 0.3s;`, notes: ["Use `ms` (milliseconds) or `s` (seconds).", "Keep UI transitions under 300ms for snappiness."], example: `.card {\n  transition-property: box-shadow;\n  transition-duration: 200ms;\n  transition-timing-function: ease;\n}` },
          { id: "transition-property", title: "transition-property", description: "Specifies which CSS properties to animate.", syntax: `transition-property: all | none | color | opacity | transform;`, notes: ["`all` transitions every animatable property — can be expensive.", "Prefer specifying individual properties."], example: `.link {\n  transition-property: color, text-decoration;\n  transition-duration: 150ms;\n}` },
          { id: "animation", title: "animation", description: "Applies a keyframe animation to an element.", syntax: `animation: name duration timing-function delay iteration-count direction;`, notes: ["Shorthand for multiple animation properties.", "Requires a `@keyframes` rule."], example: `.spinner {\n  animation: spin 1s linear infinite;\n}\n\n@keyframes spin {\n  from { transform: rotate(0deg); }\n  to   { transform: rotate(360deg); }\n}` },
          { id: "animation-name", title: "animation-name", description: "Names the `@keyframes` rule to apply.", syntax: `animation-name: keyframe-name;`, notes: ["Must match the name in the `@keyframes` rule."], example: `.fade-in {\n  animation-name: fadeIn;\n  animation-duration: 0.5s;\n}\n\n@keyframes fadeIn {\n  from { opacity: 0; }\n  to   { opacity: 1; }\n}` },
          { id: "animation-duration", title: "animation-duration", description: "Sets how long one cycle of the animation takes.", syntax: `animation-duration: 1s | 500ms;`, notes: ["Default is `0s` — animation won't play without this."], example: `.pulse {\n  animation-name: pulse;\n  animation-duration: 2s;\n}` },
          { id: "animation-iteration-count", title: "animation-iteration-count", description: "Specifies how many times the animation runs.", syntax: `animation-iteration-count: 1 | 3 | infinite;`, notes: ["`infinite` loops forever.", "Can be a decimal like `0.5` for a partial cycle."], example: `.flash {\n  animation-iteration-count: 3;\n}` },
          { id: "animation-timing-function", title: "animation-timing-function", description: "Controls the speed curve of the animation.", syntax: `animation-timing-function: linear | ease | ease-in | ease-out | ease-in-out | cubic-bezier();`, notes: ["`ease` (default): starts fast, slows down.", "`linear`: constant speed.", "`cubic-bezier()`: full custom control."], example: `.smooth {\n  animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);\n}` },
          { id: "keyframes", title: "@keyframes", description: "Defines the steps of a CSS animation.", syntax: `@keyframes name {\n  from { ... }\n  to   { ... }\n  0%   { ... }\n  50%  { ... }\n  100% { ... }\n}`, notes: ["Use percentages for multi-step animations.", "`from` = `0%`, `to` = `100%`."], example: `@keyframes slideUp {\n  from {\n    opacity: 0;\n    transform: translateY(20px);\n  }\n  to {\n    opacity: 1;\n    transform: translateY(0);\n  }\n}` },
        ],
      },
    ],
  },
  {
    id: "javascript",
    title: "JavaScript",
    color: "#fbbc05",
    subcategories: [
      {
        id: "basics",
        title: "Basics",
        color: "#FF8500",
        topics: [
          { id: "variables", title: "variables (var, let, const)", description: "Variables store data values. Use `const` by default, `let` when reassignment is needed, avoid `var`.", syntax: `const name = "Alice";\nlet count = 0;\nvar legacy = true; // avoid`, notes: ["`const` — block-scoped, cannot be reassigned.", "`let` — block-scoped, can be reassigned.", "`var` — function-scoped, hoisted. Avoid in modern JS."], example: `const pi = 3.14159;\nconst greeting = "Hello";\n\nlet score = 0;\nscore = score + 10;\n\nconst user = { name: "Alice", age: 25 }; // object IS mutable` },
          { id: "data-types", title: "data types", description: "JavaScript has 7 primitive types and Objects.", syntax: `typeof value`, notes: ["Primitives: `string`, `number`, `boolean`, `null`, `undefined`, `bigint`, `symbol`.", "Everything else is an `object` (arrays, functions, etc.)."], example: `const name = "Alice";        // string\nconst age = 25;             // number\nconst active = true;        // boolean\nconst nothing = null;       // null\nlet unset;                  // undefined\nconst big = 9007199n;       // bigint\nconst id = Symbol("id");    // symbol` },
          { id: "operators", title: "operators", description: "Symbols that perform operations on values.", syntax: `// Arithmetic: + - * / % **\n// Comparison: === !== < > <= >=\n// Logical: && || !\n// Assignment: = += -= *= /=`, notes: ["Use `===` (strict equality) instead of `==` to avoid type coercion.", "`??` (nullish coalescing): returns right side if left is `null`/`undefined`."], example: `const sum = 5 + 3;         // 8\nconst isAdult = age >= 18; // true\nconst name = input ?? "Guest"; // fallback if null/undefined\nconst both = a && b;       // true if both truthy` },
          { id: "comments", title: "comments", description: "Non-executed text for notes and documentation in code.", syntax: `// Single line comment\n\n/* Multi-line\n   comment */\n\n/** JSDoc comment */`, notes: ["Use comments to explain WHY, not WHAT (the code should explain itself).", "JSDoc (`/** */`) is used by tools to generate documentation."], example: `// Calculate the user's total score\nconst total = base + bonus;\n\n/*\n  Legacy code — do not delete.\n  Removing this breaks the auth flow.\n*/\n\n/**\n * @param {string} name - The user's name\n * @returns {string} Greeting message\n */\nfunction greet(name) {\n  return \`Hello, \${name}!\`;\n}` },
        ],
      },
      {
        id: "control-flow",
        title: "Control Flow",
        color: "#4a90e2",
        topics: [
          { id: "if", title: "if", description: "Executes a block of code if a condition is true.", syntax: `if (condition) {\n  // code\n}`, notes: ["The condition is coerced to a boolean.", "Falsy values: `false`, `0`, `''`, `null`, `undefined`, `NaN`."], example: `if (score >= 90) {\n  console.log("A grade");\n}` },
          { id: "else", title: "else", description: "Executes a block when the `if` condition is false.", syntax: `if (condition) {\n  // true\n} else {\n  // false\n}`, notes: ["The `else` block only runs when the `if` is false."], example: `if (isLoggedIn) {\n  showDashboard();\n} else {\n  showLogin();\n}` },
          { id: "else-if", title: "else if", description: "Tests additional conditions when the first `if` is false.", syntax: `if (a) {\n  // ...\n} else if (b) {\n  // ...\n} else {\n  // ...\n}`, notes: ["Chains are checked top to bottom — first match wins."], example: `if (score >= 90) {\n  grade = "A";\n} else if (score >= 80) {\n  grade = "B";\n} else if (score >= 70) {\n  grade = "C";\n} else {\n  grade = "F";\n}` },
          { id: "switch", title: "switch", description: "Matches a value against multiple cases.", syntax: `switch (value) {\n  case 'a': ...; break;\n  default: ...;\n}`, notes: ["Always add `break` unless you want fallthrough.", "`default` handles unmatched values."], example: `switch (day) {\n  case 0:\n  case 6:\n    console.log("Weekend");\n    break;\n  default:\n    console.log("Weekday");\n}` },
          { id: "for-loop", title: "for loop", description: "Repeats code a set number of times.", syntax: `for (init; condition; update) {\n  // ...\n}`, notes: ["`for...of` iterates array values; `for...in` iterates object keys."], example: `for (let i = 0; i < 5; i++) {\n  console.log(i); // 0 1 2 3 4\n}\n\n// Modern: for...of\nfor (const item of items) {\n  console.log(item);\n}` },
          { id: "while-loop", title: "while loop", description: "Repeats code while a condition is true.", syntax: `while (condition) {\n  // code\n}`, notes: ["Make sure the condition eventually becomes false to avoid infinite loops."], example: `let i = 0;\nwhile (i < 3) {\n  console.log(i);\n  i++;\n}` },
          { id: "do-while", title: "do...while", description: "Like `while`, but always executes at least once.", syntax: `do {\n  // code\n} while (condition);`, notes: ["The block runs before the condition is checked."], example: `let input;\ndo {\n  input = prompt("Enter a number:");\n} while (isNaN(input));` },
        ],
      },
      {
        id: "functions",
        title: "Functions",
        color: "#7b68ee",
        topics: [
          { id: "function-declaration", title: "function declaration", description: "Defines a named function. Hoisted to the top of its scope.", syntax: `function name(params) {\n  return value;\n}`, notes: ["Hoisted — can be called before it's defined in code.", "Has its own `this` context."], example: `function greet(name) {\n  return \`Hello, \${name}!\`;\n}\n\nconsole.log(greet("Alice")); // "Hello, Alice!"` },
          { id: "function-expression", title: "function expression", description: "Assigns a function to a variable. NOT hoisted.", syntax: `const name = function(params) {\n  return value;\n};`, notes: ["NOT hoisted — must be defined before use.", "Can be anonymous or named."], example: `const double = function(n) {\n  return n * 2;\n};\n\nconsole.log(double(5)); // 10` },
          { id: "arrow-functions", title: "arrow functions", description: "Concise function syntax introduced in ES6. Does not have its own `this`.", syntax: `const fn = (params) => expression;\nconst fn = (params) => { return value; };`, notes: ["No own `this` — inherits from surrounding scope.", "Implicit return for single expressions.", "Cannot be used as constructors."], example: `const add = (a, b) => a + b;\n\nconst double = n => n * 2; // single param: no parens needed\n\nconst greet = (name) => {\n  const msg = \`Hello, \${name}!\`;\n  return msg;\n};` },
          { id: "parameters", title: "parameters", description: "Named variables in function definitions. Arguments are the actual values passed.", syntax: `function fn(param1, param2 = defaultValue) {}`, notes: ["Default parameters: `param = value`.", "Rest parameters: `...rest` collects remaining args into an array."], example: `function createUser(name, role = "student") {\n  return { name, role };\n}\n\nfunction sum(...numbers) {\n  return numbers.reduce((a, b) => a + b, 0);\n}\n\nsum(1, 2, 3, 4); // 10` },
          { id: "return", title: "return", description: "Exits a function and optionally returns a value.", syntax: `return value;`, notes: ["A function without `return` returns `undefined`.", "Execution stops at `return`."], example: `function divide(a, b) {\n  if (b === 0) return null; // early exit\n  return a / b;\n}` },
        ],
      },
      {
        id: "objects",
        title: "Objects",
        color: "#F5B945",
        topics: [
          { id: "object-literals", title: "object literals", description: "A collection of key-value pairs enclosed in curly braces.", syntax: `const obj = {\n  key: value,\n  key2: value2,\n};`, notes: ["Keys are strings (or Symbols).", "Modern shorthand: if variable name matches key, just write the variable."], example: `const name = "Alice";\nconst user = {\n  name,          // shorthand for name: name\n  age: 25,\n  active: true,\n  address: {\n    city: "Manila",\n  },\n};` },
          { id: "properties", title: "properties", description: "Access and modify object properties using dot or bracket notation.", syntax: `obj.key\nobj["key"]`, notes: ["Use dot notation for known keys.", "Use bracket notation for dynamic/computed keys."], example: `const user = { name: "Alice", age: 25 };\n\nconsole.log(user.name);       // "Alice"\nconsole.log(user["age"]);      // 25\n\nuser.email = "a@example.com"; // add property\ndelete user.age;               // remove property` },
          { id: "methods", title: "methods", description: "Functions stored as object properties.", syntax: `const obj = {\n  greet() {\n    return "Hello!";\n  }\n};`, notes: ["Shorthand method syntax: `method() {}` instead of `method: function() {}`.", "`this` inside a method refers to the object."], example: `const counter = {\n  count: 0,\n  increment() {\n    this.count++;\n  },\n  reset() {\n    this.count = 0;\n  },\n};\n\ncounter.increment();\nconsole.log(counter.count); // 1` },
          { id: "this-keyword", title: "this keyword", description: "Refers to the current execution context (the object calling the method).", syntax: `this.property`, notes: ["`this` inside an object method refers to the object.", "`this` in arrow functions refers to the enclosing scope, not the object."], example: `const person = {\n  name: "Alice",\n  greet() {\n    return \`Hi, I'm \${this.name}\`; // "this" = person\n  },\n};` },
          { id: "json", title: "JSON", description: "JavaScript Object Notation — a text format for storing and transferring data.", syntax: `JSON.stringify(obj)  // → string\nJSON.parse(str)      // → object`, notes: ["JSON keys must be double-quoted strings.", "No functions, `undefined`, or circular references allowed."], example: `const user = { name: "Alice", age: 25 };\n\nconst json = JSON.stringify(user);\n// '{"name":"Alice","age":25}'\n\nconst parsed = JSON.parse(json);\n// { name: "Alice", age: 25 }` },
        ],
      },
      {
        id: "arrays",
        title: "Arrays",
        color: "#D94452",
        topics: [
          { id: "array-literals", title: "array literals", description: "An ordered collection of values.", syntax: `const arr = [1, 2, 3];\nconst arr = new Array(5);`, notes: ["Can hold mixed types.", "0-indexed.", "Length: `arr.length`."], example: `const fruits = ["apple", "banana", "cherry"];\nconsole.log(fruits[0]); // "apple"\nconsole.log(fruits.length); // 3` },
          { id: "push", title: "push()", description: "Adds one or more items to the END of an array. Returns new length.", syntax: `arr.push(value)`, notes: ["Mutates the original array."], example: `const arr = [1, 2];\narr.push(3);\nconsole.log(arr); // [1, 2, 3]` },
          { id: "pop", title: "pop()", description: "Removes and returns the LAST item of an array.", syntax: `arr.pop()`, notes: ["Mutates the original array."], example: `const arr = [1, 2, 3];\nconst last = arr.pop();\nconsole.log(last); // 3\nconsole.log(arr);  // [1, 2]` },
          { id: "shift", title: "shift()", description: "Removes and returns the FIRST item of an array.", syntax: `arr.shift()`, notes: ["Mutates and can be slow on large arrays (re-indexes all items)."], example: `const arr = [1, 2, 3];\nconst first = arr.shift();\nconsole.log(first); // 1\nconsole.log(arr);   // [2, 3]` },
          { id: "unshift", title: "unshift()", description: "Adds one or more items to the BEGINNING of an array.", syntax: `arr.unshift(value)`, notes: ["Mutates the array."], example: `const arr = [2, 3];\narr.unshift(1);\nconsole.log(arr); // [1, 2, 3]` },
          { id: "map", title: "map()", description: "Creates a NEW array by applying a function to each element.", syntax: `arr.map(item => newValue)`, notes: ["Does NOT mutate the original array.", "Always returns an array of the same length."], example: `const nums = [1, 2, 3];\nconst doubled = nums.map(n => n * 2);\nconsole.log(doubled); // [2, 4, 6]\n\nconst names = users.map(u => u.name);` },
          { id: "filter", title: "filter()", description: "Creates a NEW array with only items that pass the test.", syntax: `arr.filter(item => condition)`, notes: ["Does NOT mutate the original.", "Returns a subset — can be empty."], example: `const nums = [1, 2, 3, 4, 5];\nconst evens = nums.filter(n => n % 2 === 0);\nconsole.log(evens); // [2, 4]\n\nconst active = users.filter(u => u.active);` },
          { id: "reduce", title: "reduce()", description: "Reduces an array to a single value by applying a function cumulatively.", syntax: `arr.reduce((accumulator, current) => newAcc, initialValue)`, notes: ["Always provide an initial value (2nd argument).", "Can build any output: number, string, object, array."], example: `const nums = [1, 2, 3, 4];\nconst sum = nums.reduce((acc, n) => acc + n, 0);\nconsole.log(sum); // 10\n\n// Group by property\nconst grouped = users.reduce((acc, user) => {\n  (acc[user.role] ??= []).push(user);\n  return acc;\n}, {});` },
          { id: "forEach", title: "forEach()", description: "Executes a function for each element. Returns nothing.", syntax: `arr.forEach(item => { ... })`, notes: ["Unlike `map`, does NOT return anything.", "Cannot be stopped with `break` — use a `for...of` loop for that."], example: `const fruits = ["apple", "banana"];\nfruits.forEach((fruit, index) => {\n  console.log(\`\${index}: \${fruit}\`);\n});` },
        ],
      },
      {
        id: "dom",
        title: "DOM Manipulation",
        color: "#20b2aa",
        topics: [
          { id: "getElementById", title: "document.getElementById()", description: "Selects an element by its ID.", syntax: `document.getElementById("my-id")`, notes: ["Returns the element or `null` if not found.", "Fastest DOM selection method."], example: `const btn = document.getElementById("submit-btn");\nbtn.disabled = true;` },
          { id: "querySelector", title: "document.querySelector()", description: "Selects the FIRST element matching a CSS selector.", syntax: `document.querySelector(".class")\ndocument.querySelector("#id")\ndocument.querySelector("div > p")`, notes: ["`querySelectorAll()` returns ALL matching elements as a NodeList.", "Accepts any valid CSS selector."], example: `const card = document.querySelector(".card");\nconst allCards = document.querySelectorAll(".card");` },
          { id: "innerHTML", title: "innerHTML", description: "Gets or sets the HTML content inside an element.", syntax: `element.innerHTML = "<p>New content</p>";`, notes: ["⚠️ Be careful with user data — can lead to XSS attacks.", "Use `textContent` for plain text (safer)."], example: `const div = document.querySelector("#output");\ndiv.innerHTML = "<strong>Hello!</strong>";\n\n// Safer for user content:\ndiv.textContent = userInput;` },
          { id: "style-dom", title: "style", description: "Access an element's inline CSS styles.", syntax: `element.style.property = "value";`, notes: ["CSS property names become camelCase: `background-color` → `backgroundColor`.", "Better for dynamic changes; prefer CSS classes for static styling."], example: `const box = document.querySelector(".box");\nbox.style.backgroundColor = "#3b82f6";\nbox.style.transform = "scale(1.1)";` },
          { id: "addEventListener", title: "addEventListener()", description: "Attaches an event listener to an element.", syntax: `element.addEventListener("event", handler);`, notes: ["Use `removeEventListener` to clean up.", "Third parameter: `{ once: true }` fires only once."], example: `const btn = document.querySelector("button");\nbtn.addEventListener("click", (event) => {\n  console.log("Clicked!", event.target);\n});\n\n// Once only:\nbtn.addEventListener("click", handler, { once: true });` },
          { id: "createElement", title: "createElement()", description: "Creates a new HTML element in memory.", syntax: `document.createElement("tagName")`, notes: ["Must be appended to the DOM with `appendChild` or `append` to be visible."], example: `const li = document.createElement("li");\nli.textContent = "New item";\nli.className = "list-item";\n\ndocument.querySelector("ul").appendChild(li);` },
          { id: "appendChild", title: "appendChild()", description: "Adds a node as the last child of a parent element.", syntax: `parent.appendChild(child)`, notes: ["Moves the node if it already exists in the DOM.", "Use `append()` for multiple nodes or text strings."], example: `const list = document.querySelector("ul");\nconst item = document.createElement("li");\nitem.textContent = "Item 3";\nlist.appendChild(item);` },
        ],
      },
      {
        id: "events",
        title: "Events",
        color: "#9b59b6",
        topics: [
          { id: "onclick", title: "onclick", description: "Fires when an element is clicked.", syntax: `element.onclick = handler;\nelement.addEventListener("click", handler);`, notes: ["Prefer `addEventListener` over the `onclick` property — allows multiple listeners."], example: `button.addEventListener("click", () => {\n  alert("Clicked!");\n});` },
          { id: "onchange", title: "onchange", description: "Fires when the value of an `<input>`, `<select>`, or `<textarea>` changes.", syntax: `input.addEventListener("change", handler);`, notes: ["Fires on blur (when leaving the field). For real-time updates, use `oninput`."], example: `const select = document.querySelector("select");\nselect.addEventListener("change", (e) => {\n  console.log("Selected:", e.target.value);\n});` },
          { id: "onmouseover", title: "onmouseover", description: "Fires when the mouse enters an element.", syntax: `element.addEventListener("mouseover", handler);`, notes: ["Fires for the element AND its children (use `mouseenter` for just the element)."], example: `card.addEventListener("mouseover", () => {\n  card.classList.add("hovered");\n});\n\ncard.addEventListener("mouseout", () => {\n  card.classList.remove("hovered");\n});` },
          { id: "onkeydown", title: "onkeydown", description: "Fires when a keyboard key is pressed down.", syntax: `element.addEventListener("keydown", handler);`, notes: ["`event.key` gives the key name (e.g., `'Enter'`, `'Escape'`).", "`event.code` gives the physical key (e.g., `'KeyA'`)."], example: `document.addEventListener("keydown", (e) => {\n  if (e.key === "Escape") closeModal();\n  if (e.key === "Enter") submitForm();\n});` },
          { id: "onload", title: "onload", description: "Fires when the page (or an element like `<img>`) fully loads.", syntax: `window.addEventListener("load", handler);\n// or DOMContentLoaded for when HTML is ready:\ndocument.addEventListener("DOMContentLoaded", handler);`, notes: ["`DOMContentLoaded` fires earlier than `load` (no waiting for images/CSS).", "In most cases, `DOMContentLoaded` is what you want."], example: `document.addEventListener("DOMContentLoaded", () => {\n  console.log("DOM ready, initializing app...");\n  initApp();\n});` },
        ],
      },
      {
        id: "advanced",
        title: "Advanced",
        color: "#ff6b6b",
        topics: [
          { id: "es6", title: "ES6 features", description: "Key ES6 (ES2015) features: destructuring, spread, template literals, shorthand.", syntax: `const { a, b } = obj;          // destructuring\nconst [x, y] = arr;\nconst merged = { ...obj1, ...obj2 }; // spread\nconst str = \`Hello, \${name}\`;   // template literal`, notes: ["ES6+ is supported in all modern browsers.", "Use Babel to support older browsers."], example: `// Destructuring\nconst { name, age } = user;\nconst [first, ...rest] = items;\n\n// Spread\nconst newArr = [...arr, 4, 5];\nconst newObj = { ...user, age: 26 };\n\n// Template literals\nconst msg = \`Hello, \${name}! You have \${count} messages.\`;` },
          { id: "classes", title: "classes", description: "Syntactic sugar over JavaScript's prototype-based inheritance.", syntax: `class Name extends Parent {\n  constructor() { super(); }\n  method() {}\n}`, notes: ["Classes are NOT hoisted like function declarations.", "`extends` enables inheritance, `super()` calls the parent constructor."], example: `class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n  speak() {\n    return \`\${this.name} makes a sound.\`;\n  }\n}\n\nclass Dog extends Animal {\n  speak() {\n    return \`\${this.name} barks.\`;\n  }\n}` },
          { id: "modules", title: "modules (import/export)", description: "Organizes code into separate files with explicit imports and exports.", syntax: `export const x = 1;\nexport default function() {}\n\nimport { x } from './file';\nimport fn from './file';`, notes: ["Named exports: multiple per file, use `{}`.", "Default export: one per file, imported without `{}`."], example: `// utils.js\nexport const add = (a, b) => a + b;\nexport const PI = 3.14159;\n\n// main.js\nimport { add, PI } from './utils';\nconsole.log(add(2, 3)); // 5` },
          { id: "promises", title: "promises", description: "Represents the eventual result of an async operation.", syntax: `new Promise((resolve, reject) => { ... })\npromise.then(result => ...).catch(err => ...)`, notes: ["States: `pending`, `fulfilled`, `rejected`.", "Chain `.then()` for success, `.catch()` for errors."], example: `const fetchUser = (id) =>\n  new Promise((resolve, reject) => {\n    if (id > 0) resolve({ id, name: "Alice" });\n    else reject(new Error("Invalid ID"));\n  });\n\nfetchUser(1)\n  .then(user => console.log(user))\n  .catch(err => console.error(err));` },
          { id: "async-await", title: "async/await", description: "Syntactic sugar over Promises for writing async code in a synchronous style.", syntax: `async function fn() {\n  const data = await promise;\n}`, notes: ["Functions marked `async` always return a Promise.", "Use `try/catch` to handle errors."], example: `async function loadUser(id) {\n  try {\n    const res = await fetch(\`/api/users/\${id}\`);\n    const user = await res.json();\n    return user;\n  } catch (error) {\n    console.error("Failed:", error);\n    throw error;\n  }\n}` },
          { id: "fetch-api", title: "fetch API", description: "Modern browser API for making HTTP requests.", syntax: `fetch(url, options).then(res => res.json())`, notes: ["`fetch` returns a Promise.", "Always call `.json()`, `.text()`, or `.blob()` to read the body.", "Fetch only rejects on network errors — HTTP errors need to be checked manually."], example: `// GET request\nconst res = await fetch("/api/users");\nconst users = await res.json();\n\n// POST request\nconst res = await fetch("/api/users", {\n  method: "POST",\n  headers: { "Content-Type": "application/json" },\n  body: JSON.stringify({ name: "Alice" }),\n});\n\nif (!res.ok) throw new Error(\`HTTP \${res.status}\`);` },
          { id: "error-handling", title: "error handling (try...catch)", description: "Wraps code that might throw errors and handles them gracefully.", syntax: `try {\n  // risky code\n} catch (error) {\n  // handle error\n} finally {\n  // always runs\n}`, notes: ["`finally` runs whether or not an error occurred.", "Create custom errors with `throw new Error('message')`."], example: `async function saveData(data) {\n  try {\n    const res = await fetch("/api/save", {\n      method: "POST",\n      body: JSON.stringify(data),\n    });\n    if (!res.ok) throw new Error("Save failed");\n    return await res.json();\n  } catch (err) {\n    console.error("Error:", err.message);\n    showErrorToast(err.message);\n  } finally {\n    setLoading(false);\n  }\n}` },
        ],
      },
    ],
  },
];